version: '3'
services:
    swagger-ui:
        ports:
          - 8080:8080
        image: swaggerapi/swagger-ui
        restart: always
        volumes:
          - //projects/dev-utils/swagger/specs://usr/share/nginx/html/docs
        environment:
            VALIDATOR_URL: ''
            URLS_PRIMARY_NAME: pet-store
            URLS: "[{ url: \"docs/sample-api.json\", name: \"sample-api\" },
                    { url: \"https://petstore.swagger.io/v2/swagger.json\", name: \"pet-store\" },
                    { url: \"https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/uber.json\", name: \"uber\" },
                   ]"